# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_LocalAuth',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField(db_index=True)),
                ('LAuthType', models.CharField(default='', max_length=100)),
                ('UserName', models.CharField(db_index=True, max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('CTime', models.DateTimeField(auto_now_add=True)),
                ('MTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User_LocalAuth',
            },
        ),
        migrations.CreateModel(
            name='User_OpenAuth',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField(db_index=True)),
                ('NickName', models.CharField(default='', max_length=255)),
                ('OAuthType', models.IntegerField()),
                ('OAuthID', models.CharField(default='', max_length=255)),
                ('OAuth_Access_Token', models.CharField(default='', max_length=255)),
                ('OAuth_Refresh_Access_Token', models.CharField(default='', max_length=255)),
                ('OAuth_Expires', models.CharField(default='', max_length=255)),
                ('Scope', models.CharField(default='', max_length=255)),
                ('AccountPic_URL', models.CharField(default='', max_length=255)),
                ('Gender', models.IntegerField(blank=True)),
                ('Country', models.CharField(blank=True, default='', max_length=255)),
                ('Province', models.CharField(blank=True, default='', max_length=255)),
                ('City', models.CharField(blank=True, default='', max_length=255)),
                ('CTime', models.DateTimeField(auto_now_add=True)),
                ('MTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User_OpenAuth',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('NickName', models.CharField(default='', max_length=128)),
                ('LevelID', models.IntegerField()),
                ('AccountPic_URL', models.CharField(default='', max_length=255)),
                ('SelfIntroduction', models.CharField(default='', max_length=255)),
                ('Gender', models.IntegerField()),
                ('LocationProvince', models.CharField(default='', max_length=50)),
                ('LocationCity', models.CharField(default='', max_length=100)),
                ('CTime', models.DateTimeField(auto_now_add=True)),
                ('MTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
