# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='AccountPic_URL',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='LevelID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='LocationCity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='LocationProvince',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='SelfIntroduction',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
