# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluds', '0004_auto_20170828_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='LevelID',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
