# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluds', '0005_auto_20170828_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='AccountPic_URL',
            field=models.CharField(default='', max_length=255, verbose_name='\u7528\u6237\u5934\u50cfURL'),
        ),
        migrations.AlterField(
            model_name='users',
            name='CTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 21, 25, 30, 520000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.IntegerField(verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='users',
            name='LevelID',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u7528\u6237\u7ea7\u522b'),
        ),
        migrations.AlterField(
            model_name='users',
            name='LocationCity',
            field=models.CharField(default='', max_length=100, verbose_name='\u57ce\u5e02'),
        ),
        migrations.AlterField(
            model_name='users',
            name='LocationProvince',
            field=models.CharField(default='', max_length=50, verbose_name='\u7701\u4efd'),
        ),
        migrations.AlterField(
            model_name='users',
            name='MTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 21, 25, 30, 520000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='users',
            name='NickName',
            field=models.CharField(default='', max_length=128, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='users',
            name='SelfIntroduction',
            field=models.CharField(default='', max_length=255, verbose_name='\u81ea\u6211\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
    ]
